production:
  solr:
    hostname: 54.247.183.215
    port: 8080
    log_level: WARNING
    path: '/solr'

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
